create database QLTour
go
CREATE TABLE TOUR(
MSTOUR CHAR(10),
TENTOUR NVARCHAR(30),
NGAYBT DATE,
NGAYKT DATE,
PRIMARY KEY(MSTOUR),
)
GO
CREATE TABLE DAILY(
MSDL CHAR(10),
TENDL NVARCHAR(30),
MSNVQL CHAR(10),
DIACHI NVARCHAR(30),
SODT CHAR(10),
PRIMARY KEY (MSDL),
FOREIGN KEY (MSNVQL) REFERENCES DBO.NHANVIEN(MSNV),
)
GO

CREATE TABLE VE(
MSVE CHAR(10),
MSTOUR CHAR(10),
MSDL CHAR(10),
PRIMARY KEY(MSVE),
FOREIGN KEY (MSTOUR) REFERENCES DBO.TOUR(MSTOUR),
FOREIGN KEY (MSDL) REFERENCES DBO.DAILY(MSDL),
)
GO
CREATE TABLE NHANVIEN(
MSNV CHAR(10),
TENVN NVARCHAR(30),
NGAYSINH DATE,
GOITINH BIT,
DIACHI NVARCHAR(30),
SODT CHAR(10)
PRIMARY KEY (MSNV)
)
GO
CREATE TABLE KHACHHANG(
MSKH CHAR(10),
TENKH NVARCHAR(30),
GIOITINH BIT,
CCCD CHAR(12),
MSVE CHAR(10),
DIACHI NVARCHAR(30),
SODT CHAR(10)
PRIMARY KEY(MSKH, CCCD),
FOREIGN KEY (MSVE) REFERENCES DBO.VE(MSVE)

)
GO
CREATE TABLE DD_THAMQUAN(
MSDD CHAR(10),
TENDD NVARCHAR(30),
MSTOUR CHAR(10),
DIACHI NVARCHAR(30),
PRIMARY KEY (MSDD),
FOREIGN KEY (MSTOUR) REFERENCES  DBO.TOUR(MSTOUR)
)
GO
CREATE TABLE KHACHSAN(
MSKS CHAR(10),
TENKS NVARCHAR(30),
MSTOUR CHAR(10),
DIACHI NVARCHAR(30),
SODT CHAR(10),
PRIMARY KEY (MSKS),
FOREIGN KEY (MSTOUR) REFERENCES  DBO.TOUR(MSTOUR)

)
GO 
CREATE TABLE PHUONGTIEN(
MSTOUR CHAR(10),
 MSPT CHAR(10),
 LOAIPT NVARCHAR(30),
 HIENTRANG NVARCHAR(30),
 SUCCHUA INT,
 PRIMARY KEY(MSPT),
 FOREIGN KEY (MSTOUR) REFERENCES DBO.TOUR(MSTOUR),
 )
GO