INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (123, 1, 33)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (123, 2, 8)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (345, 10, 10)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (345, 20, 10)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (345, 3, 10)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (456, 1, 20)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (456, 2, 20)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (678, 3, 40)
GO
INSERT INTO PHANCONG (MaNV,MaDA,ThoiGian)
VALUES (789, 10, 35)