ALTER TABLE PHONGBAN ALTER COLUMN TenPhg nvarchar(30)
GO
ALTER TABLE DEAN ALTER COLUMN DDiemDA nvarchar(20)
GO
ALTER TABLE THANNHAN ALTER COLUMN TenTN nvarchar(20)
GO
ALTER TABLE THANNHAN ALTER COLUMN Phai nvarchar(3)
GO
ALTER TABLE THANNHAN ALTER COLUMN QuanHe nvarchar(15)